version: '3.1'
services:
  mongo:
    image: mongo:4.1.13
    restart: always
    environment:
      MONGO_INITDB_DATABASE: momenta
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 12345678
    ports:
      - "27017:27017"
    expose:
      - "27017"
    volumes:
      - ./_dev:/data/db
    networks:
      - default
networks:
  default:
    external:
      name: momenta